"""empty message

Revision ID: 5296cdd9e421
Revises: None
Create Date: 2014-12-09 00:01:34.266863

"""

# revision identifiers, used by Alembic.
revision = '5296cdd9e421'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=120), nullable=True),
    sa.Column('college_name', sa.String(length=120), nullable=True),
    sa.Column('academic_year', sa.Integer(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('eliminated', sa.Boolean(), nullable=True),
    sa.Column('first_round_answers', sa.Text(), nullable=True),
    sa.Column('first_elimination_vote', sa.Text(), nullable=True),
    sa.Column('second_round_answers', sa.Text(), nullable=True),
    sa.Column('second_elimination_vote', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('photo_url', sa.String(length=120), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('eliminated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    ### end Alembic commands ###
